# Generated by Django 2.2.5 on 2019-09-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='is_h_s',
            field=models.BooleanField(default=False, verbose_name='Получил звание руки смерти?'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Сдал тест?'),
        ),
    ]
