# Generated by Django 2.2.5 on 2019-09-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_auto_20190920_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='test',
            new_name='question',
        ),
    ]
