# Generated by Django 2.2.5 on 2019-09-21 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0003_auto_20190921_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden.Question', verbose_name='Вопрос'),
        ),
    ]
