# Generated by Django 2.2.5 on 2019-09-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0004_auto_20190921_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='sith',
            name='count_h_s',
            field=models.IntegerField(default=0, verbose_name='Количество рук тени'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(choices=[('y', 'Да'), ('n', 'Нет')], default='y', max_length=1, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden.Recruit', verbose_name='Рекрут'),
        ),
    ]
